Repository AY2223S2-CS2103T-T12-3/tp, pull requests merged in 2023-03, with the labels that each got.

#47 Add Book object and modify JSON property
  src/main/java/expresslibrary/logic/commands/EditCommand.java
  src/main/java/expresslibrary/logic/parser/AddCommandParser.java
  src/main/java/expresslibrary/logic/parser/CliSyntax.java
  src/main/java/expresslibrary/logic/parser/ParserUtil.java
  src/main/java/expresslibrary/model/person/Book.java
  src/main/java/expresslibrary/model/person/Person.java
  src/main/java/expresslibrary/model/util/SampleDataUtil.java
  src/main/java/expresslibrary/storage/JsonAdaptedPerson.java
  src/test/java/expresslibrary/logic/LogicManagerTest.java
  src/test/java/expresslibrary/logic/parser/AddCommandParserTest.java
  src/test/java/expresslibrary/logic/parser/ExpressLibraryParserTest.java
  src/test/java/expresslibrary/storage/JsonAdaptedPersonTest.java
  src/test/java/expresslibrary/storage/JsonSerializableExpressLibraryTest.java
  src/test/java/expresslibrary/testutil/PersonBuilder.java
  src/test/java/expresslibrary/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#64 Comment out test cases to update functionality, will fix later
  src/main/java/expresslibrary/model/person/Person.java
  src/test/java/expresslibrary/logic/commands/EditCommandTest.java
  src/test/java/expresslibrary/model/person/PersonTest.java
  src/test/java/expresslibrary/storage/JsonAdaptedPersonTest.java
  src/test/java/expresslibrary/storage/JsonExpressLibraryStorageTest.java
  src/test/java/expresslibrary/storage/StorageManagerTest.java
Labels: type.Task, priority.Medium

#82 Refactor code for both main and test to reflect difference in commands
  src/main/java/expresslibrary/logic/commands/AddPersonCommand.java
  src/main/java/expresslibrary/logic/commands/DeletePersonCommand.java
  src/main/java/expresslibrary/logic/commands/EditPersonCommand.java
  src/main/java/expresslibrary/logic/commands/FindPersonCommand.java
  src/main/java/expresslibrary/logic/commands/ListPersonCommand.java
  src/main/java/expresslibrary/logic/parser/AddPersonCommandParser.java
  src/main/java/expresslibrary/logic/parser/DeletePersonCommandParser.java
  src/main/java/expresslibrary/logic/parser/EditPersonCommandParser.java
  src/main/java/expresslibrary/logic/parser/ExpressLibraryParser.java
  src/main/java/expresslibrary/logic/parser/FindPersonCommandParser.java
  src/test/java/expresslibrary/logic/LogicManagerTest.java
  src/test/java/expresslibrary/logic/commands/AddPersonCommandIntegrationTest.java
  src/test/java/expresslibrary/logic/commands/AddPersonCommandTest.java
  src/test/java/expresslibrary/logic/commands/CommandTestUtil.java
  src/test/java/expresslibrary/logic/commands/DeletePersonCommandTest.java
  src/test/java/expresslibrary/logic/commands/EditPersonCommandTest.java
  src/test/java/expresslibrary/logic/commands/EditPersonDescriptorTest.java
  src/test/java/expresslibrary/logic/commands/FindPersonCommandTest.java
  src/test/java/expresslibrary/logic/commands/ListPersonCommandTest.java
  src/test/java/expresslibrary/logic/parser/AddPersonCommandParserTest.java
  src/test/java/expresslibrary/logic/parser/DeletePersonCommandParserTest.java
  src/test/java/expresslibrary/logic/parser/EditPersonCommandParserTest.java
  src/test/java/expresslibrary/logic/parser/ExpressLibraryParserTest.java
  src/test/java/expresslibrary/logic/parser/FindPersonCommandParserTest.java
  src/test/java/expresslibrary/testutil/EditPersonDescriptorBuilder.java
  src/test/java/expresslibrary/testutil/PersonUtil.java
Labels: priority.Medium

#91 Updated UG and DG to reflect changes in Person commands
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
Labels: priority.High

#107 Improve find commands
  src/main/java/expresslibrary/commons/util/StringUtil.java
  src/test/java/expresslibrary/commons/util/StringUtilTest.java
Labels: priority.Medium
